server:
  port: 8080

reactor:
  netty:
    ioWorkerCount: 4    # Количество воркер-потоков IO
    selectCount: 4      # Количество селектор-потоков

spring:
  main:
    web-application-type: reactive

# Настройки для эмулятора
emulator:
  # Настройки задержки ответа (в миллисекундах)
  delay:
    min: 100
    max: 500

# Настройки для actuator и prometheus
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true
  metrics:
    tags:
      application: emulator-service
    export:
      prometheus:
        enabled: true
    enable:
      all: true

# Настройки для OpenAPI
springdoc:
  swagger-ui:
    path: /swagger-ui.html
